### ISSUE TITLE
Missing sound on the Orion drive

### ISSUE THREAD

**Issue by JacobB094** [ChrisAdderley/FarFutureTechnologies#202]
The new Orion drive looks great, but it doesn't seem to have any sound. I do know some older Orion mods (USI, I think) did have a very satisfying "POW!" sound with every pulse. There is a reference to a stock sound file in the config, but it doesn't seem to actually play.

I'll check the other pulse engines and see if they're also affected.

**Comment by JacobB094** [comment]
None of the other pulse engines seem to have this problem, however, arcjet RCS do.

**Comment by ChrisAdderley** [comment]
It seems to make noise for me, I'll have to dig in at some point
